# Generated by Django 5.0.6 on 2024-07-21 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0003_remove_basketitem_user'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineproduct',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_lines', to='basket.basket'),
        ),
    ]
