# Generated by Django 5.0.6 on 2024-07-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_orderlineproduct_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineproduct',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(editable=False, max_length=32, unique=True),
        ),
    ]
