# Generated by Django 5.0.6 on 2024-07-27 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_orderlineproduct_quantity_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineproduct',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_lines', to='payment.order'),
        ),
    ]
