# Generated by Django 5.0.6 on 2024-08-08 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_orderlineproduct_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orginal_basket',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_pid',
            field=models.CharField(default='', max_length=254),
        ),
    ]
