# Generated by Django 5.0.6 on 2024-08-08 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_order_orginal_basket_order_stripe_pid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='orginal_basket',
            new_name='original_basket',
        ),
    ]
