# Generated by Django 5.0.6 on 2024-07-04 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainUserProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.TextField()),
                ('body_part', models.CharField(choices=[('Legs', 'Legs'), ('Chest', 'Chest'), ('Back', 'Back'), ('Abs', 'Abs'), ('Shoulders', 'Shoulders'), ('All Body', 'All Body')], default='All Body', max_length=40)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='UserPrograme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.IntegerField()),
                ('sets', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('comment', models.TextField(max_length=300)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprograms.mainuserprogram')),
            ],
        ),
    ]
