# Generated by Django 5.0.6 on 2024-07-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprograms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprograme',
            name='exercise_name',
            field=models.TextField(default='N/A'),
        ),
    ]
