# Generated by Django 5.0.6 on 2024-07-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0002_remove_profile_date_of_birth_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(default='0/00/0000'),
        ),
    ]
