# Generated by Django 5.0.6 on 2024-07-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0008_profile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(default='0000/00/00'),
        ),
    ]
