# Generated by Django 5.0.6 on 2024-08-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homenews_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homenews',
            name='title',
            field=models.TextField(max_length=100),
        ),
    ]
