# Generated by Django 5.0.6 on 2024-06-24 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PtSessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.TextField()),
                ('program', models.TextField(max_length=2000)),
                ('game', models.CharField(choices=[('Legs', 'Legs'), ('Chest', 'Chest'), ('Back', 'Back'), ('Abs', 'Abs'), ('Shoulders', 'Shoulders'), ('All Body', 'All Body')], default='All Body', max_length=40)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_sessions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
