# Generated by Django 5.0.6 on 2024-06-27 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ptsessions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ptsessions',
            old_name='game',
            new_name='body_part',
        ),
    ]
