# Generated by Django 5.0.6 on 2024-07-02 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptsessions', '0002_rename_game_ptsessions_body_part'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_in_pounds', models.PositiveIntegerField()),
                ('host_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptsessions.ptsessions')),
            ],
        ),
    ]
