# Generated by Django 5.0.6 on 2024-07-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptsessions', '0003_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ptsessions',
            name='program',
            field=models.TextField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='ptsessions',
            name='session_name',
            field=models.TextField(max_length=30),
        ),
    ]
