# Generated by Django 5.0.6 on 2024-07-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptsessions', '0005_ptsessions_price_in_pounds_delete_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ptsessions',
            name='price_in_pounds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
