# Generated by Django 5.0.6 on 2024-07-16 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptsessions', '0006_alter_ptsessions_price_in_pounds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ptsessions',
            name='price_in_pounds',
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_in_pounds', models.PositiveIntegerField()),
                ('host_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptsessions.ptsessions')),
            ],
        ),
    ]
