# Generated by Django 5.0.6 on 2024-08-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptsessions', '0012_alter_ptsessions_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptsessions',
            name='description',
            field=models.TextField(default='blank', max_length=2000),
        ),
    ]
