# Generated by Django 5.0.6 on 2024-07-23 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0004_basketitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketitem',
            name='user',
        ),
    ]
